name: Maven Java CI 
description: TODO

on:
  push:
    branches:
      - upcoming-v4
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Source checkout
        uses: actions/checkout@v3
        with:
          # depth 0 means checkout all commits... we need that 
          # in case there are many commits in a push/PR
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.9.2
        with:
          dir_names: true
          dir_names_max_depth: 2
#          quotepath: true
#          write_output_files: true
#          json: true
#          json_raw_format: true

      - name: List all changed files
        if: ${{ always() }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
