name: Maven Java CI 
description: TODO

on:
  push:
    branches:
      - upcoming-v4
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      
    steps:

      - name: Source checkout
        uses: actions/checkout@v3
        with:
          # depth 0 means checkout all commits... we need that 
          # in case there are many commits in a push/PR
          fetch-depth: 0

      - name: Get directories with changes
        id: changed-files
        uses: tj-actions/changed-files@v35.9.2
        with:
          dir_names: true
          dir_names_max_depth: 2
          write_output_files: true

      - name: Build maven projects filter argument
        # Uncomment always() if running into issues using act on a local
        # environment, until this is fixed:
        # https://github.com/tj-actions/changed-files/issues/1046 
        if: ${{ always() }}
        run: |
          echo "ARGS: $(bash .github/workflows/scripts/mvn-project-filter-args.sh)"