name: Find Copyright Files

on:
  push:
    branches:
      - dk-actions-v4

jobs:
  find-copyright:
    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.set-output.outputs.files }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Find Copyright Files
      id: set-output
      run: |
        # Find files with the specified copyright pattern
        copyright_files=$(grep -rlE 'Copyright [0-9]{4} Norconex Inc\.' .)
        echo "files_1=${copyright_files}" >> $GITHUB_ENV
        echo "::set-output name=files::${copyright_files}"

    - name: Display Copyright Files
      run: |
        # Access the output from the previous step
        files="${{ steps.set-output.outputs.files }}"
        echo "Files with Copyright (4-digit-years) Norconex Inc.:"
        echo "${files}"

    - name: Display Files_1
      run: |
        echo "files in files_1"
        for file in ${{env.files_1}}; do
          echo "$file"
        done

# Add more steps as needed for your workflow
