name: Update Copyright Year

on:
  push:
    branches:
      - dk-actions-v4

jobs:
  update-copyright-year:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Find and Update Copyright Year
      run: |
        # Find files with the specified copyright pattern
        copyright_files=$(grep -rlE 'Copyright [0-9]{4} Norconex Inc\.' .)

        # Display the files
        echo "Files with Copyright (year) Norconex Inc.:"
        while IFS= read -r file; do
          echo "${file}"
          
          # Update copyright year in each file
          sed -i "s/Copyright [0-9]\{4\} Norconex Inc\./Copyright $(date +'%Y') Norconex Inc./g" "${file}"
        done <<< "${copyright_files}"

        # Set an output variable for further use
        echo "files=${copyright_files}" >> $GITHUB_ENV

# Add more steps as needed for your workflow
