name: find modified files

on:
  push:
    branches: [ dk-actions-v4 ]
  pull_request:
    branches: [ dk-actions-v4 ]


jobs:
  get_files:
    name: run_when_pr_is_merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      
      - name: Get changed files
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
                echo "MODIFIED_JAVA_FILES=$(git diff --name-only --diff-filter=M ${{ github.event.before }} ${{ github.sha }} | grep '\.txt$')" >> $GITHUB_OUTPUT 
            else
                echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT                
                echo "MODIFIED_JAVA_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- '*.java' | xargs)" >> $GITHUB_OUTPUT
                fi

      - name: List changed files
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "$file was changed"
            echo test >> $file
            more $file
            done
          
      - name: List changed files
        run: |
          for file in ${{ steps.changed-files.outputs.MODIFIED_JAVA_FILES }}; do
            echo "$file was changed"
            echo test >> $file
            more $file
          done

      - name: Check for String in Modified Files
        run: |
          STRING_TO_CHECK="changed-files"
          NEW_LINES="new lines"

          for file in ${{ steps.changed-files.outputs.MODIFIED_JAVA_FILES }}; do
            if grep -Fxq "^\s*$STRING_TO_CHECK" "$file"; then
              echo "The string '$STRING_TO_CHECK' exists in the file: $file"
              sed -i "/$STRING_TO_CHECK/a $NEW_LINES" "$file"
              echo "Added '$NEW_LINES' after '$STRING_TO_CHECK' in $file"
            else
              echo "The string '$STRING_TO_CHECK' doesn't exist in the file: $file"
            fi
            more $file                        
          done
