name: Docker Image CI

on:
  push:
    branches: [ "dk-actions-v4" ]
  pull_request:
    branches: [ "dk-actions-v4" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: extract version no from pom.xml file
      #run: cat pom.xml | grep -m2 "version" | tail -n1 | sed 's/<.*>\(.*\)<.*>/\1/' | sed 's/^[ ]*//g' > result.txt
      run: cat pom.xml | grep -m1 "version" | sed 's/<.*>\(.*\)<.*>/\1/' | sed 's/^[ ]*//g' > result.txt

    - name: extract version no from pom.xml file - 2
      run: echo "VERSION=$(cat pom.xml | grep -m1 "version" | sed 's/<.*>\(.*\)<.*>/\1/' | sed 's/^[ ]*//g')" >> $GITHUB_ENV

    - name: check what is inside result.txt
      run: more result.txt

    - name: show variable
      run: echo "Version:${{env.VERSION}}"

    - name: manually set the env.VERSION value
      run: echo "VERSION=3.0.2" >> $GITHUB_ENV

    - name: show variable new value
      run: echo "Version:${{env.VERSION}}"
      
    - name: Download Maven Artifact
      id: download-maven-artifact
      uses: clausnz/github-action-download-maven-artifact@master
      with:
        url: 'https://repo1.maven.org'
        repository: 'maven2'
        groupId: 'com.norconex.collectors'
        artifactId: 'norconex-collector-http'
        version: ${{env.VERSION}}
        extension: 'zip'

    - name: Output file path in container
      run: echo "File has been downloaded to ${{ steps.download-maven-artifact.outputs.file }}"
           
    - name: debug
      run: |
        sudo ls -l /home/runner/work/collector-http/collector-http/  
        sudo ls -l /home/runner/work/collector-http/collector-http/crawler
        sudo ls -l /home/runner/work/collector-http/collector-http/crawler/web
        mkdir /home/runner/work/collector-http/collector-http/crawler/web/target
        sudo ls -l /home/runner/work/collector-http/collector-http/crawler/web/target


      
    - name: Move files
      run: cp ${{ steps.download-maven-artifact.outputs.file }} /home/runner/work/collector-http/collector-http/crawler/web/target/collector.zip

    - name: list file
      run: ls -l /home/runner/work/collector-http/collector-http/crawler/web/target
         
    - name: Build the Docker image
      run: docker build . --tag crawler

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: bkmyuen21/docker-test
        tags: v2
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}  
         
