name: Docker Image CI

# auto triggering spec, this required workflow placed in main branch
#on:
#  workflow_run:
#    workflows: [Maven Build & Upload]
#    types:
#      - completed
      
on:
  push:
    branches: [ "dk-actions-v4" ]
  pull_request:
    branches: [ "dk-actions-v4" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Extract the version number from the pom.xml file located in the v4-branch, this version will be used to download
    # the right version of artifact from maven repo
    - name: extract version no from pom.xml file
      #run: cat pom.xml | grep -m2 "version" | tail -n1 | sed 's/<.*>\(.*\)<.*>/\1/' | sed 's/^[ ]*//g' > result.txt
      run: cat pom.xml | grep -m1 "version" | sed 's/<.*>\(.*\)<.*>/\1/' | sed 's/^[ ]*//g' > result.txt

    - name: extract version no from pom.xml file - 2
      run: echo "VERSION=$(cat pom.xml | grep -m1 "version" | sed 's/<.*>\(.*\)<.*>/\1/' | sed 's/^[ ]*//g')" >> $GITHUB_ENV

    # debugging, can be removed in prod
    - name: check what is inside result.txt
      run: more result.txt

    - name: show variable
      run: echo "Version:${{env.VERSION}}"

    - name: manually set the env.VERSION value
      run: echo "VERSION=3.0.2" >> $GITHUB_ENV

    - name: show variable new value
      run: echo "Version:${{env.VERSION}}"

    # download the artifacts from maven repo  
    - name: Download Maven Artifact
      id: download-maven-artifact
      uses: clausnz/github-action-download-maven-artifact@master
      with:
        url: 'https://repo1.maven.org'
        repository: 'maven2'
        groupId: 'com.norconex.collectors'
        artifactId: 'norconex-collector-http'
        version: ${{env.VERSION}}
        extension: 'zip'

    # confirm where all the files are saved
    - name: Output file path in container
      run: echo "File has been downloaded to ${{ steps.download-maven-artifact.outputs.file }}"
           
    - name: create /crawler/web/target directory
      run: |
        mkdir /home/runner/work/collector-http/collector-http/crawler/web/target
        sudo ls -l /home/runner/work/collector-http/collector-http/crawler/web/target

    # copy the download files from temp location to the docker context location for use later 
    - name: Copy files from tmp to target dir
      run: cp ${{ steps.download-maven-artifact.outputs.file }} /home/runner/work/collector-http/collector-http/crawler/web/target/collector.zip

    - name: list file
      run: ls -l /home/runner/work/collector-http/collector-http/crawler/web/target

    # debug docker build cmd, remove in future     
    - name: Build the Docker image
      run: docker build . --tag crawler

    # build and upload to dockerhub
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: bkmyuen21/docker-test
        tags: v2
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}  
         
    # other docker build cmds for other image: base+ES, base+solr
