name: Docker Image CI

on:
  push:
    branches: [ "dk-actions-v4" ]
  pull_request:
    branches: [ "dk-actions-v4" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Maven Artifact
      id: download-maven-artifact
      uses: clausnz/github-action-download-maven-artifact@master
      with:
        url: 'https://repo1.maven.org'
        repository: 'maven2'
        groupId: 'com.norconex.collectors'
        artifactId: 'norconex-collector-http'
        version: '3.0.2'
        extension: 'zip'

    - name: Output file path in container
      run: |
        sudo cp ${{ steps.download-maven-artifact.outputs.file }} /var/lib/docker/tmp/buildkit-mount*
        echo "File has been downloaded to ${{ steps.download-maven-artifact.outputs.file }}"
           
    - name: debug
      run: sudo ls -l /var/lib/docker/tmp/
      
      
    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false  
        tags: nxer-web-v4:$(date +%s)
        build-args: DL_FILE=${{ steps.download-maven-artifact.outputs.file }}     
         
