name: Docker Image CI

on:
  push:
    branches: [ "dk-actions-v4" ]
  pull_request:
    branches: [ "dk-actions-v4" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Maven Artifact
      id: download-maven-artifact
      uses: clausnz/github-action-download-maven-artifact@master
      with:
        url: 'https://repo1.maven.org'
        repository: 'maven2'
        groupId: 'com.norconex.collectors'
        artifactId: 'norconex-collector-http'
        version: '3.0.2'
        extension: 'zip'

    - name: Output file path in container
      run: echo "File has been downloaded to ${{ steps.download-maven-artifact.outputs.file }}"
           
    - name: debug
      run: sudo ls -l /home/runner/work/collector-http/collector-http/  
      
    - name: Move files
      run: cp ${{ steps.download-maven-artifact.outputs.file }} /home/runner/work/collector-http/collector-http/crawler/web/target/collector.zip

    - name: list file
      run: ls -l /home/runner/work/collector-http/collector-http/crawler/web/target
         
    - name: Build the Docker image
      run: docker built -t .
         
