name: docker-build

on:
  push:
    branches: [ "dk-actions-v4" ]
  pull_request:
    branches: [ "dk-actions-v4" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: mvn-build-upload.yml
          branch: dk-actions-v4
          name: collector.zip
          path: crawler/web/target
          run_number: 5
          if_no_artifact_found: fail
                 
      - name: 'Echo download path'
        run: echo ${{steps.download-artifact.outputs.download-path}}
