name: file filter

on:
  push:
    branches: [ dk-actions-v4 ]


jobs:
  get_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: filter files
        run: |
          ls -l | grep .txt