name: test assign variable

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: check our repository
        uses: actions/checkout@v3
        
      - name: extract version no from pom.xml file
        run: cat pom.xml | grep version | sed 's/<.*>\(.*\)<.*>/\1/' | sed 's/^[ ]*//g' > result.txt

      - name: set variable
        run: |
          ver=$(cat result.txt)
          echo "Version=$ver" >> $GITHUB_ENV
       
      
