name: workflow_02

on:
  workflow_run:
    workflows: [workflow_01]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v3
  
